rename alluvial.dat %1.alv
rename outelev.dat	%1.dat
rename summary.dat	 %1.sum
rename continue.dat %1.cnt
rename gradient.dat %1.grd
rename bistable.dat %1.bis
rename resist.out %1.res
rename regolith.dat %1.reg
rename outbase.dat	%1.bse
rename deform.dat %1.dfm
rename bedrock.dat	%1.bed
rename kindex.dat %1.knd
rename topo.raw %1top.raw
rename topo.dat %1.top
rename bshade??.raw %1??.raw
rename submrg??.raw %1??_s.raw
rename qenfrc??.raw %1??_q.raw
rename relele??.raw %1??_e.raw
rename channel.dat	%1.chn
rename source.dat %1.src
rename record.dat %1.rec
rename report.prn %1.rep
rename debug.prn %1.dbg
rename qq.dat %1.qqq
rename ewater.dat %1.wat
rename lava.dat %1.lav
rename lactive.dat	%1.lct
rename lage.dat %1.lge
rename lage.raw %1lage.raw
rename basin.lst %1.lst
rename crater.dat %1.crt
rename submerge.dat %1.sub
rename sedbudget.prn %1.sbg
rename chprop.prn %1.chp
rename sedtemp.dat %1.sdt
RENAME STATISTICS.PRN %1.PRN
copy marssim.prm %1.prm
copy marssim.prm %1param.prm
copy inrates.dat %1.rte
copy inelev.dat %1.ein
pkzip -add -move %1 %1.*
